### PR TITLE
Constantine/add phone btn

### PR DESCRIPTION
**Pull request by ConstantineWang**
## Description

This PR is for issue Fix add phone button CSS #28. 

## Deployment

- [x] I am making a frontend change, which will be auto-deployed via Heroku.
- [ ] I am making a Ruby change, which will be auto-deployed via Heroku.
  - [ ] I have added one or more gems, and run `rake sorbet:update:all` to generate their types.
  - [ ] I have added or changed a model, and run `rake sorbet:update:all` to generate their types.
- [ ] I am making a database change, which I will manually deploy after my branch is merged.
  - [ ] I have migrated the database using `env RAILS_ENV=production rails db:migrate`.
  - [ ] I have updated the entity relationship diagram via `bundle exec erd`.
  - [ ] I have updated the affected Administrate model dashboards to reflect my DB changes.
- [ ] I am making a Go Lambda change, which I will manually deploy after my branch is merged.
  - [ ] I have deployed the lambdas using `make deploy`.
- [ ] There are other deployment steps I must take after merge, which are:

### CODE REVIEW

**Comment by nathanmsmith** [comment]
@ConstantineWang could you add before and after screenshots of the change?

**Comment by ConstantineWang** [comment]
@nathanmsmith 
I apologize for the delay. I had a lot of coursework to attend to. I'm now open to working on more pull requests, so feel free to assign me any issue. As promised, attached is the before and after screenshots.

Screenshot 2023-03-28 at 12 37 56 AM
Screenshot 2023-03-28 at 12 37 35 AM

**Review by nathanmsmith — APPROVED** [review]
Looks great, thanks for the screenshots! @ConstantineWang I'll let you merge.

As for next issues, what do you think about #14? There's both a front- and backend component to it. Happy to chat about it more over slack or in office hours.

**Comment by ConstantineWang** [comment]
Sure! I will work on #14 and hope to discuss it with you during office hours.

**Pull request merged**
